expose cmake options in cpptoml vendor package
eclipse/iceoryx pull request #345
Opened 2020-11-09 19:51 UTC by Karsten1987

When compiling with Clang (note, not apple-clang) there's some option within the cpptoml cmake phase. These have to exposed in the vendor package as well.

2020-11-09 20:15 UTC, elBoberido submitted a review, later dismissed

2020-11-09 20:42 UTC, dkroenke approved these changes

2020-11-09 21:37 UTC, ithier approved these changes

2020-11-09 22:08 UTC, dkroenke requested changes
@Karsten1987 You need to add the iox number to your commit message for traceability, e.g. "iox-#345 expose cmake options in cpptoml vendor package"

2020-11-09 22:39 UTC, Karsten1987 commented
how would I know my "iox-number" before opening a PR?

2020-11-10 07:21 UTC, dkroenke commented
> how would I know my "iox-number" before opening a PR? Also what happens if I have multiple commits?

First you need to have a github issue which describes what you intent to do. You can either use an existing one or create a new issue. This issue has a number which you use in your commit messages for tracing. I was not aware that there was no issue existing here.

I created a new issue for you https://github.com/eclipse/iceoryx/issues/348 which has 348 as number. You can now rework you commit messages again with this number. 
For more information about the workflow see https://github.com/eclipse/iceoryx/blob/master/CONTRIBUTING.md#feature-request-and-bugs

2020-11-10 08:54 UTC, elfenpiff approved these changes

2020-11-10 19:46 UTC, elBoberido commented
@Karsten1987 just to avoid misunderstandings and you are wondering why this is not merged, since dkronke created an issue, the commit message is supposed to start with `iox-#348`

2020-11-12 17:30 UTC, dkroenke commented
> @Karsten1987 just to avoid misunderstandings and you are wondering why this is not merged, since dkronke created an issue, the commit message is supposed to start with `iox-#348`

@Karsten1987 Would you rework your commit again with `iox-#348` as number? I will then approve and merge this PR.

2020-11-12 17:39 UTC, Karsten1987 commented
done

2020-11-12 17:58 UTC, mossmaurice approved these changes

2020-11-12 18:16 UTC, dkroenke approved these changes

2020-11-12 18:16 UTC, merged