Iox #382 remove default param from getInstance
eclipse/iceoryx pull request #396
Opened 2020-11-27 14:14 UTC by FerdinandSpitzschnueffler

## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [ ] All checks have passed
1. [ ] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Notes for Reviewer
This PR removes the default parameter from PoshRuntime::getInstance(). Therefore two new functions are introduced: 
getInstance without parameter to receive the active runtime and initRuntime to create the runtime

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [ ] All checkboxes in the PR checklist are checked or crossed out
1. [ ] Merge

## References

- Closes [#382](https://github.com/eclipse/iceoryx/issues/382)

2020-11-27 17:03 UTC, elBoberido requested changes

2020-11-27 17:03 UTC, elBoberido commented on iceoryx_posh/source/runtime/posh_runtime.cpp
> +    if (!name.has_value())
on a second thought, maybe it makes more sense to do this check in `PoshRuntime& PoshRuntime::getInstance(cxx::optional<const ProcessName_t*> name)`, right before calling `return getRuntimeFactory()(name);` and then passing just a reference to the name instead the optional

2020-11-30 07:39 UTC, budrus reviewed
should be fine when the findings of @elBoberido are addressed

2020-11-30 13:36 UTC, budrus approved these changes

2020-11-30 15:56 UTC, elBoberido approved these changes

2020-11-30 17:14 UTC, merged